### ISSUE TITLE
Add semantic release

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/pg-anonymizer#14]
We need a changelog and an automated release process on NPM. It's easy to add, I already implemented it [here](https://github.com/rap2hpoutre/csv-elasticsearch) and [there](https://github.com/rap2hpoutre/create-elasticsearch-dataset). We could roughly copy/paste the github action and [semantic release](https://github.com/semantic-release/semantic-release) configuration.

**Comment by imreACTmd** [comment]
"You cannot publish over the previously published versions: 0.5.0."
