### ISSUE TITLE
Apply ESlint fixes

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/pg-anonymizer#16]
Currently, there is an incompatible mix between prettier default and ESlint. We should rely only on ESlint, and run lint on all files.

_Side note: I have to wait for https://github.com/rap2hpoutre/pg-anonymizer/pull/13 to be merged to avoid conflicts_

**Comment by imreACTmd** [comment]
I have time to work on this, but what do you run to get the ESlint output you prefer? npm run posttest ? And is eslintrc already to your liking?

**Comment by imreACTmd** [comment]
#13 has been merged, I could start on this.

**Comment by rap2hpoutre** [comment]
> And is eslintrc already to your liking?

Not really! it's the default one provided by oclif since I used oclif to initialize the CLI (https://oclif.io/). 

Most of the time, in my other projects, I only use Prettier with VS code without changing anything or adding something else. And when I use eslint, I prefer semicolons and more "default" conf. 

In one of the products I develop currently with other devs (gov project), we choose this config and I feel like it's OK: https://github.com/betagouv/service-national-universel/blob/main/api/.eslintrc.js

Since you are currently the main contributor to this project 😅, it's also up to you. Feel free to suggest what you prefer too.

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/pg-anonymizer/pull/42 thanks to @jackall3n
