### ISSUE TITLE
Version in NPM doesn't support the options listed on github

### ISSUE THREAD

**Issue by imreACTmd** [rap2hpoutre/pg-anonymizer#28]
NPM has an 1.0.0, the semantic release has a 0.5.0, and the npm pg-anonymizer@0.5.0 doesn't match the github main version either. Could you make a manual tag of 1.0.1 maybe?

**Comment by imreACTmd** [comment]
I think I figured out how to do this, I'll tag 1.0.1

**Comment by imreACTmd** [comment]
... I managed to create a 0.5.1 tag. @rap2hpoutre can you somehow delete the 1.0.0 release from NPM?

**Comment by rap2hpoutre** [comment]
Ooops sorry for late answer

**Comment by rap2hpoutre** [comment]
It has just been unpublished! Thank you for your patience!
