### ISSUE TITLE
Ignore NULL values

### ISSUE THREAD

**Issue by fsschmitt** [rap2hpoutre/pg-anonymizer#34]
Hey 👋 

It would be cool if it would be possible to set a configuration to even when using faker's config file, to set that any field that is NULL in the DB it should remain NULL instead of generating a fake name for example.

Let me know where I can help!

Cheers!

**Comment by monta42** [comment]
Hello,

I would be happy about this addition as well. And it would be great if it would be possible to keep empty fields as empty and not replace them with random data.
Unfortunately, I don't know TS well enough to add this myself.

Cheers!

**Comment by jackall3n** [comment]
Hopefully this gets merged: https://github.com/rap2hpoutre/pg-anonymizer/pull/40/files
